name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./go

      - name: Build
        run: go build ./...
        working-directory: ./go

      - name: Run tests
        run: go test ./...
        working-directory: ./go

