name: Next.js CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./nextjs

      - name: Run ESLint
        run: npm run lint
        working-directory: ./nextjs

      - name: Build
        run: npm run build
        working-directory: ./nextjs

      - name: Run tests
        run: npm test
        working-directory: ./nextjs

