name: PHP CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Validate PHP syntax
        run: php -l wordpress/wp-content/themes/index.php

      - name: Run PHP tests
        run: |
          # Add commands to run your tests here
          # For example, if you use PHPUnit:
          # phpunit --configuration phpunit.xml
        working-directory: ./wordpress

