name: WordPress CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"
        working-directory: ./wordpress

      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 wordpress/wp-content/themes/

      - name: Validate PHP syntax
        run: php -l wordpress/wp-content/themes/index.php

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit ^9
        working-directory: ./wordpress

      - name: Run PHP tests
        run: vendor/bin/phpunit
        working-directory: ./wordpress

      - name: Build Docker image
        run: docker build -t shyamthedevopsguy/wordpress:latest ./wordpress

      - name: Push Docker image
        run: docker push shyamthedevopsguy/wordpress:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

       ...
      - name: Deploy to Staging
        if: success()
        run: |
          kubectl apply -f k8s/staging/wordpress.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}

